version: '3'

services:
  db:
    image: mysql:8.0
    container_name: hr_tool_db
    restart: always
    environment:
      MYSQL_DATABASE: hr-tool
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local